# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 20 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: charkeeper_development

local_production:
  <<: *default
  database: charkeeper_development

test:
  <<: *default
  database: charkeeper_test

production:
  <<: *default
  database: charkeeper
  username: charkeeper
  password: <%= Rails.application.credentials[:database_password] %>

ru_production:
  <<: *default
  database: charkeeper
  username: charkeeper
  password: <%= Rails.application.credentials[:database_password] %>
